# Generated by Django 3.2.3 on 2021-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.CharField(max_length=200),
        ),
    ]
