# Generated by Django 3.2.3 on 2021-07-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210724_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='item',
            new_name='realtor',
        ),
    ]
