# Generated by Django 3.2.3 on 2021-07-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_rename_item_order_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
