# Generated by Django 3.2.3 on 2021-07-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_alter_realtor_date_hired'),
        ('order', '0007_alter_order_realtor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='realtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor'),
        ),
    ]
